fixed 101-compile

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,13 +1,8 @@
-#!/usr/bin/python3
-import py_compile
-import os
-import sys
+#!/bin/bash
+python3 -c "import py_compile; py_compile.compile('$PYFILE', '$PYFILE' + 'c')"
 
-
-pyfile = os.environ['PYFILE']
-
-try:
-    py_compile.compile(pyfile, pyfile + 'c')
-    print(f"Compiling {pyfile} ...")
-except Exception as e:
-    print("Compilation failed:", e)
+if [ $? -eq 0 ]; then
+  echo "Compiling $PYFILE ..."
+else
+  echo "Compilation failed."
+fi
